---
title: "Article 1 : Use of honeybee and bumblebee venom against breast cancer"
description: |
  Scientists have found honeybee venom to rapidly destroy breast cancer cells due to their high concentration in melittin which is very efficient in reducing tumor growth
author:
  - name: Hugo De Smet
    url: {}
date: 10-25-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
**I. Source of the article**

URL : https://www.sciencedaily.com/releases/2020/09/200901093412.htm

Date : September 2, 2020

Word count : 750

**II. Vocabulary**

| *Word from the text* | *Synonym/definition in english*                               | *French translation* |
|----------------------|---------------------------------------------------------------|----------------------|
| potent               | powerful                                                      | puissant             |
| melittin             | a basic peptide which is the main component of honeybee venom | mélittine            |
| barb                 | stinger                                                       | le dard              |
| to mirror            | to have                                                       | présenter            |


**III.Analysis table about the study**

| *Reaserchers*                 | Dr Ciara Duffy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|-------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| *Published in ? When ?*       | npj Precision Oncology, September2,2020                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| *General topic*               | Efficiency of honeybee and bumblebee venom against triple-negative breast cancer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| *Procedure/what was examined* | Researchers investigated the capacity of honeybee venom to slow down breast cancer cells growth rate and even kill these cells.                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| *Conclusions/discovery*       | It appears that melittin (main component of honeybee venom) drastically reduce the viabilty of triple negative breast cancer and HER2-enriched breast cancer cells. Melittin has been found to totally destroy cancer cell membrane within 60 minutes and also considerably reduce the chemical messages of cancer cells which greatly decrease their viability. Another potential effect of melittin is that it forms holes in breast cancer cell membrane which offers a great synergy with chemoterapy drugs that would reach the inside of cancer cells and kill them way easier. |
| *Remaining question*          | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
::
